[package]
name = "loader"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
ctrlc = "3.4.2"
elf = "0.7.4"
env_logger = "0.11.2"
libc = "0.2.153"
log = "0.4.21"
