[build]
linker = "rust-lld"
target = "riscv32im-unknown-none-elf"
rustflags = ["-C", "link-args=--nmagic"]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]