[build]
target = "armv7-unknown-linux-musleabihf"

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "target-feature=+crt-static", "-C", "linker=ld.lld", "-C", "relocation-model=static", "-C", "strip=symbols"]
